# Generated by Django 5.0.6 on 2024-07-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('empfname', models.CharField(max_length=64)),
                ('emplname', models.CharField(max_length=64)),
                ('emppasswd', models.CharField(max_length=64)),
                ('emprole', models.IntegerField()),
            ],
            options={
                'db_table': 'kadai1_employee',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medicineid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('medicinename', models.CharField(blank=True, max_length=64, null=True)),
                ('unit', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'kadai1_medication',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('patfname', models.CharField(max_length=64)),
                ('patlname', models.CharField(max_length=64)),
                ('hokenmei', models.CharField(max_length=64)),
                ('hokenexp', models.DateField()),
            ],
            options={
                'db_table': 'kadai1_patient',
            },
        ),
        migrations.CreateModel(
            name='Tabyouin',
            fields=[
                ('tabyouinid', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('tabyouinmei', models.CharField(max_length=64)),
                ('tabyouinaddress', models.CharField(max_length=64)),
                ('tabyouintel', models.CharField(max_length=13)),
                ('tabyouinshihonkin', models.CharField(max_length=13)),
                ('kyukyu', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'kadai1_tabyouin',
            },
        ),
    ]
