# Generated by Django 5.0.6 on 2024-07-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadai1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication_K',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanzyaid', models.CharField(max_length=8)),
                ('kanzyaname', models.CharField(max_length=64)),
                ('kanzyafname', models.CharField(max_length=64)),
                ('kanzyalname', models.CharField(max_length=64)),
                ('kanzyahokenmei', models.CharField(max_length=64)),
                ('kanzyahokenexp', models.DateField()),
                ('kanzyamedid', models.CharField(max_length=8)),
                ('kanzyamedname', models.CharField(blank=True, max_length=64, null=True)),
                ('medcount', models.DateField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'kadai1_Medication_K',
            },
        ),
    ]
